language: node_js

sudo: false

node_js:
- '4.0'
- '4.3'
- '5.0'
- '5.5'
- '5.7'
- '5.11'
- '6.0'

cache:
  directories:
  - node_modules

notifications:
  email: false

before_install:
  - npm update -g npm

after_script:
  - npm run publish-codeclimate
  - npm run publish-codacy