language: node_js

sudo: false

node_js:
- '4.0'
- '4.1'
- '4.2'
- '4.3'
- '5.0'
- '5.1'
- '5.2'
- '5.3'
- '5.4'
- '5.5'
- '5.6'
- '5.7'
- iojs
- node

cache:
  directories:
  - node_modules

notifications:
  email: false

before_install:
  - npm update -g npm

after_script:
  - npm run publish-codeclimate
  - npm run publish-codacy